<nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-home" href="#home" role="button">
                <svg class="lnr lnr-home"><use xlink:href="#lnr-home"></use></svg>
            </a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#scroll-spy" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <i class="material-icons">&#xE5D2;</i>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="scroll-spy">

            <ul class="nav navbar-nav ">
                <li><a href="#about">À propos</a></li>
                <li><a href="#demo">Demo</a></li>
                <li><a href="#features">Features</a></li>
                <li><a href="#howto">How to</a></li>
            </ul>
        </div>
    </div>
</nav>

<script src="./javascriptfile/navbar.js"></script>